### ISSUE TITLE
Request to shorten the dashboard nginx ingress uid

### ISSUE THREAD

**Issue by ianmuge** [DevOps-Nirvana/Grafana-Dashboards#10]
When running this as a provisioned dashboard the dashboard doesnt get loaded because of the length of the uid resulting in:

```
logger=provisioning.dashboard type=file name=default t=2025-03-07T17:30:39.524130667Z level=error msg="failed to save dashboard" file=/var/lib/grafana/dashboards/default/nginx-ingress.json error="uid too long, max 40 characters"
```
Config used:
```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    ...
    nginx-ingress:
      gnetId: 14314
      datasource: Prometheus
```
